encoding: "utf-8"
#You appear to have pagination turned on, but you haven't included the `jekyll-paginate` gem. Ensure you have `gems: [jekyll-paginate]` in your configuration file.
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ===寻找心灵栖息之所
email: admin@llango.com
description:  一个为你的心灵提供栖息之所的轻应用，由langoft.com创建，在这里你能看到很多大家写的文章，诗歌，或其他文学形式，主要采用图文并茂的形式呈现，目前基本上是每日一篇，目的为了让你在这个浮华的世界里找到自己的心灵栖所．
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://llango.com" # the base hostname & protocol for your site

# Build settings
permalink: /:year/:month/:day/:title/
markdown: kramdown
paginate: 1



gems: [jekyll-paginate]